server:
  host: 0.0.0.0
  port: 8085
  metricsPort: 9085

db:
  driver: postgres
  url: host=postgresql port=5432 user=vdonate_user password=tA*i4w6$23UXDfTy^75ZGjK5WsN!qrG4 dbname=dev sslmode=disable

logger:
  level: info