server:
  host: 0.0.0.0
  port: 1234
  cert_path: "/etc/letsencrypt/live/vdonate.ml/fullchain.pem"
  key_path: "/etc/letsencrypt/live/vdonate.ml/privkey.pem"

db:
  driver: postgres
  url: host=postgresql port=5432 user=ubuntu password=secretkey dbname=dev sslmode=disable

logger:
  level: info

deploy:
  mode: true
