// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/posts.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2022_2_VDonate/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockPostsUseCase is a mock of PostsUseCase interface.
type MockPostsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPostsUseCaseMockRecorder
}

// MockPostsUseCaseMockRecorder is the mock recorder for MockPostsUseCase.
type MockPostsUseCaseMockRecorder struct {
	mock *MockPostsUseCase
}

// NewMockPostsUseCase creates a new mock instance.
func NewMockPostsUseCase(ctrl *gomock.Controller) *MockPostsUseCase {
	mock := &MockPostsUseCase{ctrl: ctrl}
	mock.recorder = &MockPostsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostsUseCase) EXPECT() *MockPostsUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostsUseCase) Create(post models.Post, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", post, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPostsUseCaseMockRecorder) Create(post, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostsUseCase)(nil).Create), post, userID)
}

// DeleteByID mocks base method.
func (m *MockPostsUseCase) DeleteByID(postID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockPostsUseCaseMockRecorder) DeleteByID(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockPostsUseCase)(nil).DeleteByID), postID)
}

// GetPostByID mocks base method.
func (m *MockPostsUseCase) GetPostByID(postID uint64) (models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByID", postID)
	ret0, _ := ret[0].(models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByID indicates an expected call of GetPostByID.
func (mr *MockPostsUseCaseMockRecorder) GetPostByID(postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByID", reflect.TypeOf((*MockPostsUseCase)(nil).GetPostByID), postID)
}

// GetPostsByUserID mocks base method.
func (m *MockPostsUseCase) GetPostsByUserID(id uint64) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByUserID", id)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByUserID indicates an expected call of GetPostsByUserID.
func (mr *MockPostsUseCaseMockRecorder) GetPostsByUserID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByUserID", reflect.TypeOf((*MockPostsUseCase)(nil).GetPostsByUserID), id)
}

// Update mocks base method.
func (m *MockPostsUseCase) Update(post models.Post, postID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", post, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPostsUseCaseMockRecorder) Update(post, postID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostsUseCase)(nil).Update), post, postID)
}
