server:
  host: 0.0.0.0
  port: 8080
  cert_path: "/etc/letsencrypt/live/vdonate.ml/fullchain.pem"
  key_path: "/etc/letsencrypt/live/vdonate.ml/privkey.pem"

logger:
  level: info

deploy:
  mode: true

services:
  auth:
    port: 8081
    host: auth
  donates:
    port: 8082
    host: donates
  images:
    port: 8083
    host: images
  posts:
    port: 8084
    host: posts
  subscribers:
    port: 8085
    host: subscribers
  subscriptions:
    port: 8086
    host: subscriptions
  users:
    port: 8087
    host: users

cors:
  allow_methods: [
    "POST",
    "GET",
    "DELETE",
    "PUT",
  ]
  allow_origins: [
    "https://vdonate.ml",
    "http://localhost:8080",
    "https://localhost:8080",
    "http://localhost:4200",
  ]
  allow_credentials: true
  allow_headers: [
    "Content-Type",
    "Content-length",
    "X-CSRF-Token",
  ]

csrf:
  enabled: false
  token_length: 32
  context_key: csrf
  context_name: csrf_token
  max_age: 86400
