DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS author_subscriptions;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS donates;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_info;
