server:
  host: 0.0.0.0
  port: 8080
  cert_path: ""
  key_path: ""

db:
  driver: postgres
  url: host=localhost port=5432 user=ubuntu password=secretkey dbname=dev sslmode=disable

logger:
  level: info

deploy:
  mode: false

s3:
  endpoint: localhost:9000
  access_key_id: admin
  secret_access_key: secretkey
  use_ssl: false
  # Declare polices of buckets here
  buckets:
    img: ""
    avatar: >-
      {"Version": "2012-10-17","Statement": [{"Action": ["s3:GetObject"],"Effect": "Allow","Principal": {"AWS": ["*"]},"Resource": ["arn:aws:s3:::avatar/*"],"Sid": ""}]}
