server:
  host: 127.0.0.1
  port: 8080

db:
  driver: postgres
  url: host=localhost dbname=dev sslmode=disable

debug:
  cors: false

#server:
#  host: 127.0.0.1
#  port: 81
#
#db:
#  driver: postgres
#  url: host=localhost password=123456 dbname=dev sslmode=disable
#
#debug:
#  cors: true