server:
  host: 0.0.0.0
  port: 8080
  cert_path: "/etc/letsencrypt/live/vdonate.ml/fullchain.pem"
  ket_path: "/etc/letsencrypt/live/vdonate.ml/privkey.pem"

db:
  driver: postgres
  url: host=postgres port=5432 user=ubuntu password=secretkey dbname=dev sslmode=disable

logger:
  level: debug

deploy:
  mode: true

s3:
  endpoint: 0.0.0.0/cloud
  access_key_id: admin
  secret_access_key: secretkey
  use_ssl: true