server:
  host: 0.0.0.0
  port: 8080
  cert_path: ""
  ket_path: ""

db:
  driver: postgres
  url: host=postgresql port=5432 user=ubuntu password=secretkey dbname=dev sslmode=disable

logger:
  level: debug

deploy:
  mode: false
