global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'api'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'api:8079' ]

  - job_name: 'auth'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'auth:9081' ]

  - job_name: 'donates'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'donates:9082' ]

  - job_name: 'images'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'images:9083' ]

  - job_name: 'posts'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'posts:9084' ]

  - job_name: 'subscribers'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'subscribers:9085' ]

  - job_name: 'subscriptions'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'subscriptions:9086' ]

  - job_name: 'users'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'users:9087' ]

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: [ "node-exporter:9100" ]