global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["api:8080"]

#  - job_name: "node"
#    static_configs:
#      - targets: ["node-exporter:9100"]
