server:
  host: 0.0.0.0
  port: 8087
  metricsPort: 9087

db:
  driver: postgres
  url: host=postgresql port=5432 user=vdonate_user password=secretkey dbname=dev sslmode=disable
  max_idle_conns: 2
  max_open_conns: 1

logger:
  level: info