{
 "title": "VDonate-HTTP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "HTTP RPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(echo_requests_total[2m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, url, job) (rate(echo_requests_total{job=\"api\"}[2m]))",
     "legendFormat": "{{job}} - {{method}} - {{url}}"
    }
   ]
  },
  {
   "title": "RPS - 2XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, code) (rate(echo_requests_total{code=~\"2..\"}[2m]))",
     "legendFormat": "{{job}} - {{code}}"
    }
   ]
  },
  {
   "title": "RPS - 2XX By URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code, job, url) (rate(echo_requests_total{code=~\"2..\"}[2m]))",
     "legendFormat": "{{job}} - {{code}} - {{url}}"
    }
   ]
  },
  {
   "title": "RPS - 4XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, code) (rate(echo_requests_total{code=~\"4..\"}[2m]))",
     "legendFormat": "{{job}} - {{code}}"
    }
   ]
  },
  {
   "title": "RPS - 4XX by URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code, url, job) (rate(echo_requests_total{code=~\"4..\"}[2m]))",
     "legendFormat": "{{job}} - {{code}} - {{url}}"
    }
   ]
  },
  {
   "title": "RPS - 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code, job) (rate(echo_requests_total{code=~\"5..\"}[2m]))",
     "legendFormat": "{{job}} - {{code}}"
    }
   ]
  },
  {
   "title": "RPS - 5XX by URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, code, url) (rate(echo_requests_total{code=~\"5..\"}[2m]))",
     "legendFormat": "{{job}} - {{code}} - {{url}}"
    }
   ]
  },
  {
   "title": "Latency by URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(url) (rate(echo_request_duration_seconds_count{job=\"api\"}[2m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latency by Method + URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method, url) (rate(echo_request_duration_seconds_sum{job=\"api\", url=~\"/api/v1/.*\"}[2m]))",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  }
 ]
}