{
 "title": "VDonate-GRPC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Service", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "HTTP RPS",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_service) (rate(grpc_client_handled_total[2m]))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "RPS by Method",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_method, grpc_service) (rate(grpc_client_handled_total[2m]))",
     "legendFormat": "{{grpc_service}}- {{grpc_method}}"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(job) (rate(grpc_server_handled_total{job=\"$job\", grpc_code!=\"OK\"}[2m])) * 100) / sum by(job) (rate(grpc_server_handled_total{job=\"$job\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS - OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(grpc_server_handled_total{job=\"$job\", grpc_code=\"OK\"}[2m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RPS - OK by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job, grpc_method) (rate(grpc_server_handled_total{job=\"$job\", grpc_code=\"OK\"}[2m]))",
     "legendFormat": "{{job}} - {{grpc_method}}"
    }
   ]
  },
  {
   "title": "RPS - Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_code, job) (rate(grpc_server_handled_total{job=\"$job\", grpc_code!=\"OK\"}[2m]))",
     "legendFormat": "{{job}} - {{grpc_code}}"
    }
   ]
  },
  {
   "title": "RPS - Error by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_method, job) (rate(grpc_server_handled_total{job=\"$job\", grpc_code!=\"OK\"}[2m]))",
     "legendFormat": "{{job}} .{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(grpc_server_handling_seconds_sum{job=\"$job\"}[2m]))",
     "legendFormat": "{{grpc_service}}"
    }
   ]
  },
  {
   "title": "Latency by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, grpc_method) (rate(grpc_server_handling_seconds_sum{job=\"$job\"}[2m]))",
     "legendFormat": "{{job}}.{{grpc_method}}"
    }
   ]
  }
 ]
}