{
 "title": "vdonate.ml",
 "description": "VDonate service dashboard",
 "tags": [ "vdonate" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "timeseries",
   "description": "The filesystem space available to non-root users (in bytes)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(device) (node_filesystem_avail_bytes)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(mode) (rate(node_cpu_seconds_total{mode=\"system\"}[1m]))",
     "legendFormat": "CPU - {{mode}}"
    }
   ]
  },
  {
   "title": "Golang",
   "type": "timeseries",
   "description": "Bytes allocation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}} - alloc bytes" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[2m])",
     "legendFormat": "{{job}} - alloc bytes total"
    },
    { "expr": "sum by(job) (go_goroutines)", "legendFormat": "{{job}} -goroutines" },
    {
     "expr": "sum by(quantile, job) (rate(go_gc_duration_seconds{quantile!~\"0|1\"}[2m]))",
     "legendFormat": "{{job}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "URL and METHODS metrics",
   "type": "timeseries",
   "description": "histogram errors, RPS of all HTTP and GRPC requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (rate(echo_requests_total[2m]))",
     "legendFormat": "{{job}} - all methods"
    },
    {
     "expr": "sum by(method, job, url) (rate(echo_requests_total[2m]))",
     "legendFormat": "{{job}} - {{method}} {{url}}"
    },
    {
     "expr": "sum by(job, method, url) (rate(echo_requests_total{code=~\"4..\"}[2m]))",
     "legendFormat": "{{job}} - {{method}} {{url}} code: 4**"
    },
    {
     "expr": "sum by(job, method, url) (rate(echo_requests_total{code=~\"5..\"}[2m]))",
     "legendFormat": "{{job}} - {{method}} {{url}} code: 5**"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, job) (rate(echo_request_duration_seconds_bucket[10m])))",
     "legendFormat": "{{job}} - quantile 0.99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, job) (rate(echo_request_duration_seconds_bucket[10m])))",
     "legendFormat": "{{job}} - quantile 0.5"
    },
    {
     "expr": "sum by(job) (rate(grpc_client_handled_total[2m]))",
     "legendFormat": "grpc_{{job}} - all methods"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, job, url, method) (rate(echo_request_duration_seconds_bucket[10m])))",
     "legendFormat": "{{job}} - {{method}} {{url}} quantile 0.99"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, job, instance) (rate(echo_request_duration_seconds_bucket[10m])))",
     "legendFormat": "from {{instance}} quantile 0.99"
    }
   ]
  }
 ]
}