name: actions
on: [ push ]

jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Setup the environment
        run: go mod download && go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -c configs/.golangci.yaml
  build:
    name: build
    needs: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Build the project
        run: make local_build
  test:
    name: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Installing mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0
      - name: Setup mocks
        run: make mocks
      - name: Testing
        run: make cover_out
      - name: Coverage check
        env:
          TESTCOVERAGE_THRESHOLD: 10
        run: |
          echo "Checking test coverage is above threshold..."
          echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=`make cover_out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current test coverage : $totalCoverage %"
          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more tests or adjust threshold to a lower value."
              echo "Failed"
              exit 1
          fi