name: deploy

on: [ workflow_dispatch ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "deployments/docker-compose.yaml, migrations/full_up.sql, .env, configs/, scripts/"
          target: "backend"
          rm: true

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker rm -f $(sudo docker ps -aq)
            sudo docker pull zeronethunter/vdonate-api
            sudo docker pull zeronethunter/vdonate-auth
            sudo docker pull zeronethunter/vdonate-images
            sudo docker pull zeronethunter/vdonate-posts
            sudo docker pull zeronethunter/vdonate-subscribers
            sudo docker pull zeronethunter/vdonate-subscriptions
            sudo docker pull zeronethunter/vdonate-users
            sudo docker pull zeronethunter/vdonate-notifications
            cd ~/backend/deployments
            PG_SUBSCRIPTIONS_PASSWORD=${{ secrets.PG_SUBSCRIPTIONS_PASSWORD }} \
            PG_AUTHOR_SUBSCRIPTIONS_PASSWORD=${{ secrets.PG_AUTHOR_SUBSCRIPTIONS_PASSWORD }} \
            PG_USERS_PASSWORD=${{ secrets.PG_USERS_PASSWORD }} \
            PG_AUTH_PASSWORD=${{ secrets.PG_AUTH_PASSWORD }} \
            PG_NOTIFICATIONS_PASSWORD=${{ secrets.PG_NOTIFICATIONS_PASSWORD }} \
            PG_POSTS_PASSWORD=${{ secrets.PG_POSTS_PASSWORD }} \
            PG_SUBSCRIPTIONS_USER=${{ secrets.PG_SUBSCRIPTIONS_USER }} \
            PG_AUTHOR_SUBSCRIPTIONS_USER=${{ secrets.PG_AUTHOR_SUBSCRIPTIONS_USER }} \
            PG_USERS_USER=${{ secrets.PG_USERS_USER }} \
            PG_AUTH_USER=${{ secrets.PG_AUTH_USER }} \
            PG_NOTIFICATIONS_USER=${{ secrets.PG_NOTIFICATIONS_USER }} \
            PG_POSTS_USER=${{ secrets.PG_POSTS_USER }} \
            docker-compose -f deployments/docker-compose.yaml up -d